-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 15:49:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  `Senha` INT NOT NULL,
  `Foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  UNIQUE INDEX `Foto_UNIQUE` (`Foto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_tema` (
  `id_tema` BIGINT NOT NULL AUTO_INCREMENT,
  `Genero` VARCHAR(255) NOT NULL,
  `Categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagem` (
  `id_postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `Titulo_Livro` VARCHAR(255) NOT NULL,
  `Descricao` VARCHAR(500) NULL,
  `Foto` VARCHAR(500) NULL,
  `Autor` VARCHAR(255) NULL,
  `codigo_tb_usuario` BIGINT NOT NULL,
  `codigo_tb_tema` BIGINT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_Postagem_tb_Usuario1_idx` (`codigo_tb_usuario` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_tema1_idx` (`codigo_tb_tema` ASC) VISIBLE,
  CONSTRAINT `fk_tb_Postagem_tb_Usuario1`
    FOREIGN KEY (`codigo_tb_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_tema1`
    FOREIGN KEY (`codigo_tb_tema`)
    REFERENCES `mydb`.`tb_tema` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
